#:wq:wq This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

#ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "julz-mjej-effz-gxr"
ENV["SLACK_WEBHOOK_URL"] = "https://hooks.slack.com/services/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"


platform :ios do

# 배포

  desc "Push a new release build to the App Store"
    lane :release do
      get_certificates
      get_provisioning_profile
      cocoapods(use_bundle_exec: false)
      build_app(workspace: "Nobar.xcworkspace", scheme: "Nobar")
      upload_to_testflight
      version = get_version_number
      send_slack({"version": version })
  end

  lane :send_slack do |options|
    slack(
      message: "앱이 App Store Connect에 성공적으로 업로드 되었습니다.",
      channel: "#1_ios_distribution",
      slack_url: ENV["SLACK_WEBHOOK_URL"],
      payload: {
        "Version": options[:version]
      }
    )
  end





  
  # match 갱신 - git에 push (certificate, profile visioning)

  private_lane :renew_codesign do|options|
    match(type:options[:type], force_for_new_devices: true)
  end

  lane :renew_codesign_debug do
    renew_codesign(type:"development")
  end
  
  lane :renew_codesign_release do
    renew_codesign(type:"appstore")
  end

  # match 로드 (certificate, profile visioning)

  private_lane :sync_codesign do|options|
    match(type:options[:type], readonly: true)
  end

  lane :sync_codesign_debug do 
    sync_codesign(type:"development")
  end

  lane :sync_codesign_release do
    sync_codesign(type:"appstore")
  end
end
